version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379

  # NestJS service
  stock-monitor-server:
    build: ./stock-monitor-server
    container_name: stock-monitor-server
    restart: unless-stopped
    ports:
      - 1337:1337
    working_dir: /app
    entrypoint: ["npm", "run", "start"]
    env_file:
      - docker-compose.env

  # NextJS application
  stock-monitor-ui:
    build: ./stock-monitor-ui
    container_name: stock-monitor-ui
    restart: unless-stopped
    ports:
      - 3000:3000
    working_dir: /app
    entrypoint: ["npm", "run", "start"]
    env_file:
      - docker-compose.env
 